### ISSUE TITLE
No feedback to user on competition admission request

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-ios#3]
I clicked on a competition to request admission. No feedback received but I verified that the admission request was correctly recorded from the backend. I expect:
 1. A message to be shown to the user to report positive request registration
 2. Changed icon/text to show the new state of the competition (pending approval)

**Comment by pragmaware** [comment]
To finish integrating firebase I need the configuration files.
Can you give me access to the firebase console?

**Comment by giohappy** [comment]
@pragmaware permissions granted for the smb-app Firebase console.

**Comment by pragmaware** [comment]
Yep, notifications are integrated. I just have to test them.
By the way... how do I win a competition?

**Comment by giohappy** [comment]
@pragmaware here we're not talkin gabout notifications but handling responses from server. The request process currently is not managed through notifications.

What I mean is to manage the (at least) 1) a positive feedback the request has been correctly subitted (synchronously) and 2) change of state/icons.

**Comment by pragmaware** [comment]
Done.
