### ISSUE TITLE
Issues in Bike detail view

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-ios#4]
1. In case no locations have been detected we shouldn't show the empty map, or at least we should show a message saying that no locations have been registered. An empty map is misleading and leaves the user with no clues.

2. What are the labels "Details" and "Vehicle" for? 

![image](https://user-images.githubusercontent.com/571129/63762185-afca6b80-c8c2-11e9-9c5b-60eeb21ca914.png)

The Android app shows the list of locations (in case they're available) otherwise "Nessuna posizione rilevata" is shown.

![image](https://user-images.githubusercontent.com/571129/63762472-1e0f2e00-c8c3-11e9-930d-9a00594882a4.png)

![image](https://user-images.githubusercontent.com/571129/63762486-223b4b80-c8c3-11e9-9a72-3c1bb5a3c96a.png)

**Comment by giohappy** [comment]
Please @pragmaware use graphics as similar as possible tp the Android app. I see you're latest changes add a marker and a question mark when no observations are available. We prefer the way we did it for Android: no map and a simple message centred on the page. 
Moreover I see a strange behaviour when I slide up the page: 
1. the top part of the card goes over the top border, so it's hidden
2. I'm not able to slide down again. It bounces and remains "slided up"
See image below

![image](https://user-images.githubusercontent.com/571129/63839085-e4036200-c97e-11e9-8504-e48c631153cc.png)

**Comment by pragmaware** [comment]
Well, I have split that in two tabs as currently on android you don't have any informations on the bike (what bike is it? is it stolen? etc...). I'll change the appearance of the page when there are no observations.

**Comment by pragmaware** [comment]
The layout of the observations list was obviously broken, I've fixed it.
