### ISSUE TITLE
Show the tracks tab when Tracks button is clicked

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-ios#5]
Currently the "Recording" tab is shown when the user clicks the "Tracks" button on the home.

![image](https://user-images.githubusercontent.com/571129/63762649-7b0ae400-c8c3-11e9-9c11-23043578cdef.png)

**Comment by pragmaware** [comment]
Ah, by the way... in iOS the tracks are uploaded automatically, without the user needing to start the operation by pushing a button. Is it OK?
Since the operation is automatic and is rather likely that the upload will succeed, the TO SEND tab is almost always empty. Do we still need it?

**Comment by giohappy** [comment]
@pragmaware what in case the upload fails? How the user will be notified and what action can he take to try again?

**Comment by pragmaware** [comment]
Right, there is no notification at the moment. The app just retries automatically several (spaced) times.

**Comment by giohappy** [comment]
so in case of failure it will retry silently forever without notifying the user?
