### ISSUE TITLE
Different bike card graphics between entering and exiting view

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-ios#7]
When I click the Bikes button the cards are shown as below:

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/b35cf0b5-526c-4882-b097-3be2a8535cce)

After I click on it (opening the bike details) and then get back to the list view I get this:

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/e625816d-1fa0-4c07-a472-032c47316745)

**Comment by pragmaware** [comment]
Yep, the gray square is the selection marker of the list view. You can have multiple bikes there.
If you want I can remove the selection though.

**Comment by giohappy** [comment]
please remove it. It doesn't look nice now, I prefer an unstyled list. 
In any case the list should be consistent on enter and leave....

**Comment by pragmaware** [comment]
Done.
